name: A workflow for my Hello World file
on: push
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Anthony"
  
  render:
    name: Screenshot Website
    runs-on: ubuntu-latest
    steps:
      - name: Screenshot Website Step
        uses: swinton/screenshot-website@v1.x
        with:
          source: https://cynthiasam.com/
          destination: screenshot.png

  healthcheck:
    runs-on: ubuntu-latest
    name: Check for status 200 and title text "Cynthia Sam"
    steps:
      - uses: actions/checkout@v2
      - id: test
        uses: johnlokerse/website-healthcheck@v2
        with:
          web-url: "https://cynthiasam.com"
          scan-for-text: "Cynthia Sam"

  security:
    runs-on: ubuntu-latest
    steps:
      - name: Test for public javascript library vulnerabilities 
        uses: lirantal/is-website-vulnerable@master
        with:
          scan-url: "https://cynthiasam.com"
