name: A workflow for my Hello World file
on: push
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Anthony"
  
  render:
    name: Screenshot
    runs-on: ubuntu-latest
    steps:
      - name: Taking Website Screenshot
        uses: swinton/screenshot-website@v1.x
        with:
          source: https://cynthiasam.com/
          destination: screenshot.png

  healthcheck:
    runs-on: ubuntu-latest
    name: Status Checks 
    steps:
      - uses: actions/checkout@v2
      - id: test
        uses: johnlokerse/website-healthcheck@v2
        with:
          web-url: "https://cynthiasam.com"
          scan-for-text: "Cynthia Sam"


  lighthouse:
    runs-on: ubuntu-latest
    name: Lighthouse
    steps:
      - uses: actions/checkout@v2
      - name: Running Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v8
        with:
          urls: |
            https://cynthiasam.com/
          budgetPath: ./budget.json # test performance budgets
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage

  speedtest:
    runs-on: ubuntu-latest
    name: Page Speed Insights
    steps:
      - name: Running Page Speed Insights
        uses: jakepartusch/psi-action@v1.2
        id: psi
        with:
          url: "https://cynthiasam.com"
          threshold: 70
          strategy: mobile
          key: ${{ secrets.PAGESPEEDINSIGHTS }}

  lumberjack:
    name: Lumberjack Audit
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Install required Linux packages
        run: |
          sudo apt-get update
          sudo apt-get install libgbm-dev
          sudo apt-get install xvfb
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install npm packages
        run: |
          npm ci
      - name: Build
        run: |
          npm run build
      - name: Running Accessibility Audits
        run: |
          npm install -g @jakepartusch/lumberjack
          xvfb-run --auto-servernum lumberjack --url ${{ secrets.PUBLIC_WEB_URL }}
